sudo: required
dist: buster
language: generic
before_install:
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev
  - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install 3.6.10
  - pyenv install 3.7.7
  - pyenv install 3.8.6
  - pyenv install 3.9.0
  - pyenv local 3.9.0 3.8.6 3.7.7 3.6.10
  - pip install pipx
  - pipx install poetry
install:
  - poetry install
  - poetry run coverage erase
script:
  - poetry run tox
afeter_success:
  - poetry run coverage combine
  - poetry run coverage report
  - poetry run coveralls
